services:
  postgres:
    image: postgres:15-alpine
    container_name: northwind-postgres
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind
      POSTGRES_PASSWORD: northwind123
    ports:
      - "5432:5432"
    volumes:
      - ./infra/docker/postgres/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U northwind -d northwind"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: northwind-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mcp-server:
    build:
      context: ./apps/mcp-server
      dockerfile: Dockerfile
    container_name: northwind-mcp-server
    environment:
      DATABASE_URL: postgresql://northwind:northwind123@postgres:5432/northwind
      PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy

  ai-orchestrator:
    build:
      context: ./apps/ai-orchestrator
      dockerfile: Dockerfile
    container_name: northwind-ai-orchestrator
    environment:
      MCP_SERVER_URL: http://mcp-server:8001
      PORT: 8002
    ports:
      - "8002:8002"
    depends_on:
      - mcp-server

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: northwind-backend
    environment:
      DATABASE_URL: postgresql://northwind:northwind123@postgres:5432/northwind
      MCP_SERVER_URL: http://mcp-server:8001
      AI_ORCHESTRATOR_URL: http://ai-orchestrator:8002
      REDIS_URL: redis://redis:6379/0
      PORT: 8000
      GCP_PROJECT_ID: portifolio-482811
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcp-key.json
    ports:
      - "8000:8000"
    volumes:
      - ./gcp-key.json:/app/gcp-key.json:ro
      - ./dbt:/app/dbt
      - ./scripts:/app/scripts
      - ./airflow:/app/airflow
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mcp-server:
        condition: service_started
      ai-orchestrator:
        condition: service_started

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: northwind-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: northwind-gateway
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - mcp-server

  prometheus:
    image: prom/prometheus:latest
    container_name: northwind-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro

volumes:
  postgres_data:
