name: 'northwind_dw'
version: '1.0.0'
config-version: 2

profile: 'northwind_dw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  northwind_dw:
    # Bronze layer - raw data ingested from source
    bronze:
      +materialized: table
      +tags: ["bronze", "raw"]
      +schema: northwind_bronze
    
    # Silver layer - cleaned and transformed data
    silver:
      +materialized: table
      +tags: ["silver", "cleaned"]
      +schema: northwind_silver
    
    # Gold layer - business aggregations and metrics
    gold:
      +materialized: table
      +tags: ["gold", "business"]
      +schema: northwind_gold